name: HotWheels Bot

on:
  schedule:
    - cron: '30 22,0,3-17 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: pip install -r requirements.txt

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python hotwheels_bot.py

      - name: Commit updated history file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add seen_cars.txt
          git commit -m "Update seen cars" || echo "No changes"
          git push
